apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignImage
metadata:
  name: solution-initcontainers-drupal
spec:
  applyTo:
    - groups: [""]
      versions: ["v1"]
      kinds: ["Pod"]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values: ["drupal"]
        - key: tier
          operator: In
          values: ["drupal"]
  location: 'spec.initContainers[name:init-site-root].image'
  parameters:
    assignDomain: "artifactory.ssc-spc.gc.ca"
    assignPath: "docker/alpine"
    assignTag: ":3.10"
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignImage
metadata:
  name: solution-initcontainers-drupal-nginx
spec:
  applyTo:
    - groups: [""]
      versions: ["v1"]
      kinds: ["Pod"]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values: ["drupal"]
        - key: tier
          operator: In
          values: ["frontend"]
  location: 'spec.initContainers[name:init-site-root].image'
  parameters:
    assignDomain: "artifactory.ssc-spc.gc.ca"
    assignPath: "docker/alpine"
    assignTag: ":3.10"
